name: skill_swap
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  supabase_flutter: ^2.9.1
  image_picker: ^1.0.5
  path: ^1.8.3
  mime: ^1.0.4
  geolocator: ^10.1.0
  geocoding: ^4.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
